 buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.1'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.application'

android {
    compileSdk 33

    defaultConfig {
        applicationId "com.meuapp.localizador"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['.']
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
